ALIGN_BOTTOM_CENTER = 1
ALIGN_CENTER_CENTER = 2
ALIGN_TOP_CENTER = 3
ALIGN_TOP_LEFT = 4
ALIGN_BOTTOM_RIGHT = 5

CATEGORY_DEFAULT = 0x0001
CATEGORY_CHARACTER = 0x0002
CATEGORY_PROJECTILE = 0x0004
CATEGORY_WEAPON = 0x0008

MASK_DEFAULT = 0xFFFF
MASK_CHARACTER = CATEGORY_DEFAULT ^ CATEGORY_PROJECTILE
MASK_PROJECTILE = CATEGORY_DEFAULT ^ CATEGORY_CHARACTER
MASK_WEAPON = 0

FILTER_DEFAULT = ( CATEGORY_DEFAULT, MASK_DEFAULT )
FILTER_CHARACTER = ( CATEGORY_CHARACTER, MASK_CHARACTER )
FILTER_PROJECTILE = ( CATEGORY_PROJECTILE, MASK_PROJECTILE )
FILTER_WEAPON = ( CATEGORY_WEAPON, MASK_WEAPON )
